version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: 
      - "5432:5432"
    volumes: 
      - pg_data:/var/lib/postgres
    networks:
      - default

  app: 
    build: .
    user: node:node
    depends_on: 
      - db
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - default
    command: "npm start"

networks:
  default: 
volumes:
  pg_data: {}
